# エラー対処 {#error}

## Build Bookを実行しても途中で止まるエラー {#error_bbstop}

### セクションヘッダーに漢字が含まれる場合に発生 {#error_bbstop_kanji}

* 発生する環境が再現できないが，以下のエラーが出てBuild Bookが途中でとまる

> file.exists(f) ここに文字化けの文字列  <Anonymous> ... move_files_html -> local_resources -> grep -> unique -> file.exists

* 対処法
    + 参考: [更新R包后，使用bookdown时出现编译失败问题请教](https://d.cosx.org/d/420961-r-bookdown) （中国語なのでgoogle翻訳を使うと何となく分かる）
    + 漢字が含まれる**セクションヘッダーには，必ず識別子**をつける
      * 例： `# 参考サイト {#sanko}`
      * 例： 番号をつけたくない場合は`# はじめに {-#hajime}`
      * 参考: マルチバイト文字についての注意 [bookdown: Authoring Books and Technical Documents with R Markdown 4.5 Internationalization](https://bookdown.org/yihui/bookdown/internationalization.html)

### tlmgrをアップデートして下さいと言われる {#error_bbstop_tlmgr}

* 以下のエラーが出てBuild Bookが途中でとまる

>tlmgr itself needs to be updated.
Please do this via either
  tlmgr update --self

* 対処法
    + `tinytex::tlmgr_update()` tinytexの関数を使ってアップデート
    
### geometryについてのエラーが出る {#error_bbstop_geo}

* 以下のエラーが出てBuild Bookが途中でとまる

> ! LaTeX Error: Option clash for package geometry.

* 対処法
    + 参考[RStudioを用いたRMarkdownによる日本語PDFファイル出力のために必要なこと](https://qiita.com/smina2018/items/0aaa56a448c95e87f6a7)
    + rmarkdown 2.x以上ではYAMLヘッダーで`geometry: no`を付けない
    + ~~参考: [Bookdownによる技術系同人誌執筆](https://teastat.blogspot.com/2019/01/bookdown.html)~~
    + ~~Buid BookでPDFを作成した後に表示されるメッセージの中のtemplateの参照先を確認~~ → rmarkdown 2.x以降は出てこない
    + ~~テンプレートは自分の環境では，パッケージが入っているフォルダの，rmarkdown > rmd > latexのフォルダ中に入っていた。これをテキストエディタ等で開く~~
    + ~~`\usepackage[$for(geometry)$$geometry$$sep$,$endfor$]{geometry}`の行頭に`% `をつけてコメントアウトするだけ~~


